# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5942e33f7f03a644e57b1aca5c8d11a8d1661b35a9df3064b9167cf62c6defc1f6604503d0c025ca46e243de5320921958aab3a0c4ef712247e6aeb6467b87b

test:
  secret_key_base: bbc151694a0c52cf87eed02da2152b6a45d89a1ed058550ee3a1fd7fcdd493fa27e4c018f4019f2361073face6a13bb67d12a0af51671e37505e56f85dc7f44b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
