class CreateFireCertifications < ActiveRecord::Migration
  def change
    create_table :fire_certifications do |t|
			t.string :ssn
			t.string :employee_id
			t.string :structure
			t.string :sf_level
			t.string :sf_received_date
			t.string :sf_expiration
			t.string :arff_cert
			t.string :arff_level
			t.string :arff_received
			t.string :arff_expiration
			t.string :fire_instructor
			t.string :fi_level
			t.string :fi_received_date
			t.string :fi_expiration
			t.string :fire_and_arson
			t.string :fai_level
			t.string :fai_received_date
			t.string :fai_expiration
			t.string :fire_cause_and
			t.string :fcoi_level
			t.string :fcoi_received
			t.string :fcoi_expiration
			t.string :fire_inspector_1
			t.string :fire_inspector_2
			t.string :fire_inspector_3
			t.string :fire_inspector_4
			t.string :hazmat
			t.string :hazmat_level
			t.string :hazmat_received
			t.string :hazmat_expiration
			t.string :hazmat_ics_1
			t.string :hazmat_ics_2
			t.string :incident_safety
			t.string :iso_received_date
			t.string :iso_expiration
			t.string :so_received_date
			t.string :driver_operator
			t.string :d_o_received_date
			t.string :d_o_expiration
			t.string :tcfp_officer_i_1
			t.string :tcfp_officer_i_2
			t.string :tcfp_officer_i_3
			t.string :tcfp_officer_ii_1
			t.string :tcfp_officer_ii_2
			t.string :tcfp_officer_ii_3
			t.string :tcfp_wildland
			t.string :tcfp_wildland_ff_1
			t.string :tcfp_wildland_ff_2
			t.string :tcfp_wildland_ff_3
			t.string :safety_officer
			t.string :ifsac_fi
			t.string :ifsac_fii
			t.string :ifsac_hma
			t.string :ifsac_hmo
			t.string :ifsac_hmt
			t.string :ifsac_do
			t.string :ifsac_arff
			t.string :ifsac_foi
			t.string :ifsac_foii
			t.string :ifsac_finv
			t.string :swiftwater
			t.string :confined_space
			t.string :trench_rescue
			t.string :rope_rescue
			t.string :pump_ops
			t.string :aerial_ops
			t.string :tcfp_examiner_1
			t.string :tcfp_examiner_2
			t.string :tcfp_examiner_3
			t.string :hazmat_ic
			t.string :hazmat_ic_rdate
			t.string :hazmat_ic_edate
      t.timestamps null: false
    end
  end
end
